---
name: Service
description: Services, or a service application, can be started automatically at system boot, by a user through the services control panel applet, or by an application that uses service functions. Services can execute even when no user is logged into the system.
fields:
  - name: service_name
    description: The name of the service.
    example: RpcSs
  - name: uid
    description: 'The ID or SID of the user '
    example: S-1-5-18
  - name: user
    description: >-
    The user context in which the thread that caused this event was running. May
    be a local, domain or SYSTEM user. Formatted as “<DOMAIN>\<USER>”. Because
    threads are allowed to impersonate users, this may be different than the
    user context of the process. For service events, the user is almost always
    NT AUTHORITY\SYSTEM
    example: NT AUTHORITY\SYSTEM
